export const CHANGE_ORIGIN = "CHANGE_ORIGN";
export const ASSIGN_INSTANCE = "ASSIGN_INSTANCE";
export const INITIALIZE_DEVICES = "INITIALIZE_DEVICES";
export const OPEN_DRIVER_BINDER = "OPEN_DRIVER_BINDER";
export const CLOSE_DRIVER_BINDER = "CLOSE_DRIVER_BINDER";
export const GET_AVAILABLE_DRIVERS = "GET_AVAILABLE_DRIVERS";
export const SELECT_DEVICE = "SELECT_DEVICE";
export const REMOVE_DEVICE = "REMOVE_DEVICE";
export const BIND_DEVICE = "BIND_DEVICE";
export const REDIRECT = "REDIRECT";

export const LOADING = "LOADING";