export const TO_SCREEN = "TO_SCREEN";

export const FILE_GET_FILE = "FILE_GET_FILE";
export const FILE_GET_AREAS = "FILE_GET_AREAS";
export const FILE_GET_DEVICE_TYPES = "FILE_GET_DEVICE_TYPES";
export const FILE_ADD_INSTANCE = "FILE_ADD_INSTANCE";
export const FILE_ADD_DEVICE = "FILE_ADD_DEVICE";
export const FILE_ADD_EVENT = "FILE_ADD_EVENT";

export const APP_ADD_DRIVER = "APP_ADD_DRIVER";
export const APP_UPDATE_SIDEBAR = "APP_UPDATE_SIDEBAR";
export const APP_UPDATE_LOG = "APP_UPDATE_LOG";
export const APP_UPDATE_SOCKET = "APP_UPDATE_SOCKET";
export const APP_ADD_USER_ID = "APP_ADD_USER_ID";
export const APP_UPDATE_DEVICE_COUNT = "APP_UPDATE_DEVICE_COUNT";
export const APP_UPDATE_INSTANCE_COUNT = "APP_UPDATE_INSTANCE_COUNT";

export const CHANGE_PERMISSIONS = "CHANGE_PERMISSIONS";

export const GET_MANIFEST = "GET_MANIFEST";
export const GET_DEVICEMAP = "GET_DEVICEMAP";

export const LOADING = "LOADING";

export const APP_UPDATE_PROGRESS = "APP_UPDATE_PROGRESS";